"""Initial schema: tweets, rss_articles, ingestion_log

Part of: Stock Sentiment Analysis Dashboard
Author: Tjoet Aliya Lakmana

Revision ID: 001
Revises:
Create Date: 2026-05-28

TimescaleDB upgrade path (Phase 5):
    SELECT create_hypertable('tweets',       'created_at');
    SELECT create_hypertable('rss_articles', 'ingested_at');
Both calls are safe because the columns are already TIMESTAMPTZ and the
GIN indexes on `tickers` are retained by TimescaleDB.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ------------------------------------------------------------------ #
    # tweets                                                               #
    # ------------------------------------------------------------------ #
    op.create_table(
        "tweets",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("author_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retweet_count", sa.Integer(), nullable=True, server_default="0"),
        sa.Column("like_count", sa.Integer(), nullable=True, server_default="0"),
        sa.Column(
            "tickers",
            postgresql.ARRAY(sa.String()),
            nullable=True,
            server_default="{}",
        ),
        sa.Column(
            "raw_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_tweets_created_at", "tweets", ["created_at"])
    op.create_index(
        "ix_tweets_tickers",
        "tweets",
        ["tickers"],
        postgresql_using="gin",
    )

    # ------------------------------------------------------------------ #
    # rss_articles                                                         #
    # ------------------------------------------------------------------ #
    op.create_table(
        "rss_articles",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_name", sa.String(length=100), nullable=True),
        sa.Column(
            "tickers",
            postgresql.ARRAY(sa.String()),
            nullable=True,
            server_default="{}",
        ),
        sa.Column(
            "raw_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url", name="uq_rss_articles_url"),
    )
    op.create_index("ix_rss_articles_ingested_at", "rss_articles", ["ingested_at"])
    op.create_index("ix_rss_articles_source_name", "rss_articles", ["source_name"])
    op.create_index(
        "ix_rss_articles_tickers",
        "rss_articles",
        ["tickers"],
        postgresql_using="gin",
    )

    # ------------------------------------------------------------------ #
    # ingestion_log                                                        #
    # ------------------------------------------------------------------ #
    op.create_table(
        "ingestion_log",
        sa.Column(
            "id",
            sa.Integer(),
            sa.Identity(always=False),  # GENERATED BY DEFAULT AS IDENTITY
            nullable=False,
        ),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column(
            "run_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=True,
        ),
        sa.Column("records_fetched", sa.Integer(), nullable=True, server_default="0"),
        sa.Column("records_stored", sa.Integer(), nullable=True, server_default="0"),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_ingestion_log_run_at", "ingestion_log", ["run_at"])
    op.create_index("ix_ingestion_log_source", "ingestion_log", ["source"])


def downgrade() -> None:
    op.drop_table("ingestion_log")
    op.drop_table("rss_articles")
    op.drop_table("tweets")
